---
- hosts: '{{ hosts }}'
  remote_user: root
#  sudo: yes
  tasks:
     - authorized_key: user=root key="{{ lookup('file', '/root/.ssh/authorized_keys' ) }}" path=/root/.ssh/authorized_keys manage_dir=no state=present
